item {
  id: 1
  name: 'Miagao Church'
}

item {
  id: 2
  name: 'Paoay Church'
}

item {
  id: 3
  name: 'San Agustin Church'
}

item {
  id: 4
  name: 'Sta. Maria Church'
}

item {
  id: 5
  name: 'Environmental Damage'
}

item {
  id: 6
  name: 'Under Construction'
}

item {
  id: 7
  name: 'Crack'
}

item {
  id: 8
  name: 'Unfinished Paint'
}

